version: '3'
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/site
    ports:
      - "8080:80"
    links:
      - database

  database:
    image: mysql:5.6
    environment:
      - "MYSQL_DATABASE=web"
      - "MYSQL_USER=web"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "33061:3306"

